language: python

python:
  - "3.6"

install:
  - pip install -r dockers/requirements.txt  # install testing requirements
  - pip install .                            # install guacamol benchmark

script:
  # Style guide enforcement
  - flake8 guacamol && flake8 tests
  # Static typing enforcement
  - mypy guacamol && mypy tests
  # Test suite
  - python -m pytest tests